import {
  errorSchema,
  healthCheckSchema,
  signInInputSchema,
  signInOutputSchema,
  validateTokenOutputSchema,
  loginPasswordInputSchema,
  loginPasswordOutputSchema,
  sendOtpTokenInputSchema,
  sendOtpTokenOutputSchema,
  validateOtpTokenInputSchema,
  validateOtpTokenOutputSchema,
  loginClientInputSchema,
  loginClientOutputSchema,
  validateClientInputSchema,
  validateClientOutputSchema,
  validatePasswordTokenOutputSchema,
  sendSmsInputSchema,
  sendSmsOutputSchema,
  validateClientTokenInputSchema,
  validateClientTokenOutputSchema,
  validatePasswordTokenInputSchema,
  tokenOutputSchema
} from './schemas/'

export default {
  error: errorSchema,
  healthCheck: healthCheckSchema,
  signInInput: signInInputSchema,
  signInOutput: signInOutputSchema,
  validateTokenOutput: validateTokenOutputSchema,
  loginPasswordInput: loginPasswordInputSchema,
  loginPasswordOutput: loginPasswordOutputSchema,
  sendOtpTokenInput: sendOtpTokenInputSchema,
  sendOtpTokenOutput: sendOtpTokenOutputSchema,
  validateOtpTokenInput: validateOtpTokenInputSchema,
  validateOtpTokenOutput: validateOtpTokenOutputSchema,
  loginClientInput: loginClientInputSchema,
  loginClientOutput: loginClientOutputSchema,
  validateClientInput: validateClientInputSchema,
  validateClientOutput: validateClientOutputSchema,
  validatePasswordTokenOutput: validatePasswordTokenOutputSchema,
  sendSmsInput: sendSmsInputSchema,
  sendSmsOutput: sendSmsOutputSchema,
  validateClientTokenInput: validateClientTokenInputSchema,
  validateClientTokenOutput: validateClientTokenOutputSchema,
  validatePasswordTokenInput: validatePasswordTokenInputSchema,
  tokenOutput: tokenOutputSchema
}
