FROM node:14.18.0-alpine3.11

RUN apk add --no-cache bash

# For NewRelic
RUN apk add --no-cache python2 build-base

# For windows
RUN touch /root/.bashrc | echo "PS1='w$ '" >> /root/.bashrc

RUN npm config set cache /home/node/app/.npm-cache --global

# For global dependencies
RUN npm install -g typescript nodemon ts-prune npm-check

RUN mkdir -p /home/node/app

USER node

WORKDIR /home/node/app
